# Matrix Credentials Secret
#
# IMPORTANT: Before applying, encode your Matrix token:
#   echo -n 'syt_cm9ja2V0_XzWbCNyOtYnBHDzEnmrL_0PYMhI' | base64
#
# Usage:
#   kubectl create secret generic matrix-credentials \
#     --from-literal=token='syt_cm9ja2V0_XzWbCNyOtYnBHDzEnmrL_0PYMhI' \
#     --from-literal=server='http://srv1:8008' \
#     --from-literal=user='@rocket:srv1.local' \
#     --from-literal=room='!UCEurIvKNNMvYlrntC:srv1.local' \
#     -n rocket

apiVersion: v1
kind: Secret
metadata:
  name: matrix-credentials
  namespace: rocket
type: Opaque
stringData:
  token: "syt_cm9ja2V0_XzWbCNyOtYnBHDzEnmrL_0PYMhI"
  server: "http://srv1:8008"
  user: "@rocket:srv1.local"
  room: "!UCEurIvKNNMvYlrntC:srv1.local"
